/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactFormSubmission {
  'name' : string,
  'email' : string,
  'serviceInterest' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface LoanApplication {
  'photoFile' : string,
  'aadharCardFile' : string,
  'employeeType' : string,
  'loanAmount' : string,
  'dateOfBirth' : string,
  'motherName' : string,
  'loanType' : string,
  'signatureFile' : string,
  'aadharNumber' : string,
  'fatherName' : string,
  'timestamp' : Time,
  'panNumber' : string,
  'tenure' : string,
  'lastName' : string,
  'panCardFile' : string,
  'loanPurpose' : string,
  'monthlyIncome' : string,
  'firstName' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminLogin' : ActorMethod<[string, string], string>,
  'adminLogout' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllLoanApplications' : ActorMethod<[string], Array<LoanApplication>>,
  'getAllSubmissions' : ActorMethod<[string], Array<ContactFormSubmission>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminPassword' : ActorMethod<[string, string], boolean>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'submitLoanApplication' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'validateAdminSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];