/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const LoanApplication = IDL.Record({
  'photoFile' : IDL.Text,
  'aadharCardFile' : IDL.Text,
  'employeeType' : IDL.Text,
  'loanAmount' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'motherName' : IDL.Text,
  'loanType' : IDL.Text,
  'signatureFile' : IDL.Text,
  'aadharNumber' : IDL.Text,
  'fatherName' : IDL.Text,
  'timestamp' : Time,
  'panNumber' : IDL.Text,
  'tenure' : IDL.Text,
  'lastName' : IDL.Text,
  'panCardFile' : IDL.Text,
  'loanPurpose' : IDL.Text,
  'monthlyIncome' : IDL.Text,
  'firstName' : IDL.Text,
});
export const ContactFormSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'serviceInterest' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllLoanApplications' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LoanApplication)],
      ['query'],
    ),
  'getAllSubmissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitLoanApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const LoanApplication = IDL.Record({
    'photoFile' : IDL.Text,
    'aadharCardFile' : IDL.Text,
    'employeeType' : IDL.Text,
    'loanAmount' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'motherName' : IDL.Text,
    'loanType' : IDL.Text,
    'signatureFile' : IDL.Text,
    'aadharNumber' : IDL.Text,
    'fatherName' : IDL.Text,
    'timestamp' : Time,
    'panNumber' : IDL.Text,
    'tenure' : IDL.Text,
    'lastName' : IDL.Text,
    'panCardFile' : IDL.Text,
    'loanPurpose' : IDL.Text,
    'monthlyIncome' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const ContactFormSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'serviceInterest' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllLoanApplications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LoanApplication)],
        ['query'],
      ),
    'getAllSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitLoanApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'validateAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };